fix: added npm audit fixes
contentstack/datasync-content-store-aws-s3 pull request #4
Opened 2022-09-26 05:59 UTC by vkalta

2022-10-28 12:57 UTC, netrajpatel requested changes
@vkalta update package versions

2022-10-30 20:34 UTC, vkalta commented
> @vkalta update package versions

Done @netrajpatel .

2022-10-31 10:31 UTC, netrajpatel approved these changes

2022-10-31 10:33 UTC, aravindbuilt approved these changes

2022-10-31 13:57 UTC, merged